config/routes.rb
Rails.application.routes.draw do
  get 'activity/index'
  
  get 'activity/:id', to: 'activity#show', as: 'activity_show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'activity#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/polyline.rb
class Polyline < ApplicationRecord
  
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def index
    if activities_params["days"]
      days = activities_params["days"].to_i || 1
      ending_date_range = 1.days.ago.end_of_day
      beginning_date_range = days.days.ago

      results = Polyline.all.where(
        "activity_started_at_date_time BETWEEN ? AND ?", 
        beginning_date_range,
        ending_date_range
      )    
    end

    if activities_params["begin"]
      beginning_date = DateTime.parse(activities_params["begin"]).beginning_of_day
      ending_date = DateTime.parse(activities_params["end"]).end_of_day


      results = Polyline.all.where(
        "activity_started_at_date_time BETWEEN ? AND ?", 
        beginning_date,
        ending_date
      )    
    end

    if results.nil?
      results = Polyline.all
    end
    # results = Polyline.all


    if results
      @polylines = results.to_json.html_safe
    else
      @polylines = "".to_json.html_safe
    end
  end

  def show
    @polyline = Polyline.find(params[:id]).to_json.html_safe
  end

  private

    def activities_params
      params.permit(:days, :month, :begin, :end, :latlng, :zoom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity/index.html.erb
<div class="filters">
<ul>
  <div class="by_time">
 <li><%= link_to "root", root_path %> </li>
 <li><%= link_to "last 10 days", "?days=10"  %> </li>
 <li><%= link_to "last 30 days", "?days=30"  %> </li>
 <li><%= link_to "last 60 days", "?days=60"  %>  </li>
 <li><%= link_to "january 2023 activity", "?begin=20230101&end=20230131"  %> </li>
 <li><%= link_to "february 2023 activity", "?begin=20230201&end=20230228"  %> </li>
 <li><%= link_to "march 2023 activity", "?begin=20230301&end=20230331"  %> </li>
 <li><%= link_to "april 2023 activity", "?begin=20230401&end=20230430"  %> </li>
 <li><%= link_to "2020 activity", "?begin=20200101&end=20201231"  %> </li>
 <li><%= link_to "2021 activity", "?begin=20210101&end=20211231"  %> </li>
 <li><%= link_to "2022 activity", "?begin=20220101&end=20221231"  %> </li>
 <li><%= link_to "2023 activity", "?begin=20230101&end=20231231"  %> </li>
 </div>
 <div class="by_location">
 <li><%= link_to "seattle", "?latlng=47.606201,-122.322671&zoom=18"  %> </li>
 <li><%= link_to "denver", "?latlng=39.681635,-105.040421&zoom=18"  %> </li>
 <li><%= link_to "bali", "?latlng=-8.507687,115.261011&zoom=18"  %> </li>
 <li><%= link_to "oslo", "?latlng=59.916448,10.752065&zoom=18"  %> </li>
 </div>
</ul>
</div>




 <div id="map">
 <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br> <br> <br> <br> <br> <br> <br> <br><br><br> there
 <br> <br>
 </div>
     <script>
      window.polylines = "<%= j @polylines %>"
      var paramsArray = window.location.search.slice(1).split("&")
      
      var queryParams = {}
      for(var i = 0; i < paramsArray.length; i++) {
        var split = paramsArray[i].split("=")

        queryParams[split[0]] = split[1]
      };

      

      
      if (queryParams["latlng"]){
       var latlng = queryParams["latlng"]
      } else { 
       var latlng = "39.681635,-105.040421"
      }

      if (queryParams["zoom"]){
        var zoom = queryParams["zoom"]
      } else {
        var zoom = "14"
      }
      
      
      var map = L.map('map').setView( latlng.split(","), zoom);
      L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 22,
        minZoom: 1,
        id: 'mapbox/satellite-v9',
        tileSize: 512,
        zoomOffset: -1,
        accessToken: 'pk.eyJ1Ijoiam9zaHdvcmtzIiwiYSI6ImNrcWk2NzUxeTJhbm8yem4weDFreTY5bjQifQ.Qja1F9B1-i7hK3KOvSYAvg'
      }).addTo(map);

      
      decoded = JSON.parse(window.polylines)
      var i = 0
      var polyline_count = decoded.length
      var lines

        for (let run of decoded) {
          i += 1
          
          var coordinates = L.Polyline.fromEncoded(run["summary"]).getLatLngs();
          var line = L.polyline(
            coordinates,
            {
                color: randbow(polyline_count, i),
                weight: 3,
                opacity: .7,
                lineJoin: 'round'
            }
          ).addTo(map);
          // marker = L.marker(coordinates[0]).addTo(map)

          var initialStyles = line.options

          line.on('mouseover', function(e){
            var popup = L.popup();
            popup.setContent(run["activity_name"] + "<a href=\"33\">run</a>");

            this.bindPopup(popup);
            popup.setLatLng(e.latlng).openOn(map);
            this.setStyle({
              weight: 7,
              opacity: 2
            })
          });

          line.on('mouseout', function(e) {
            this.setStyle({
              weight: 3, 
              opacity: .7

              });

            e.target.closePopup();
          });
      
        }


        /**
         * @param numOfSteps: Total number steps to get color, means total colors
         * @param step: The step number, means the order of the color
         */
        function randbow(numOfSteps, step) {
            // This function generates vibrant, "evenly spaced" colours (i.e. no clustering). This is ideal for creating easily distinguishable vibrant markers in Google Maps and other apps.
            // Adam Cole, 2011-Sept-14
            // HSV to RBG adapted from: http://mjijackson.com/2008/02/rgb-to-hsl-and-rgb-to-hsv-color-model-conversion-algorithms-in-javascript
            var r, g, b;
            var h = step / numOfSteps;
            var i = ~~(h * 6);
            var f = h * 6 - i;
            var q = 1 - f;
            switch(i % 6){
                case 0: r = 1; g = f; b = 0; break;
                case 1: r = q; g = 1; b = 0; break;
                case 2: r = 0; g = 1; b = f; break;
                case 3: r = 0; g = q; b = 1; break;
                case 4: r = f; g = 0; b = 1; break;
                case 5: r = 1; g = 0; b = q; break;
            }
            var c = "#" + ("00" + (~ ~(r * 255)).toString(16)).slice(-2) + ("00" + (~ ~(g * 255)).toString(16)).slice(-2) + ("00" + (~ ~(b * 255)).toString(16)).slice(-2);
            return (c);
        }


        // add start/finish marker to map via `coordinates``
        // https://code.dblock.org/2018/02/17/auto-publishing-strava-runs-to-github-pages.html


        map.on('click', function(e){
        var lt = String(e.latlng.lat);
        var lg = String(e.latlng.lng);
        var popup = L.popup()
          .setLatLng(e.latlng)
          .setContent(lt + "," + lg)
          .openOn(map);
      });

      function changeUrl(key, value){
        if ('URLSearchParams' in window) {
          var searchParams = new URLSearchParams(window.location.search);
          searchParams.set(key, value);
          window.location.search = searchParams.toString();
      }}
     </script>

<h1>Activity#index</h1>
<p>Find me in app/views/activity/index.html.erb</p>

<table>
  <tr>
    <th>Activity Name </th>         
    <th>Started At </th>                      
    <th>detail </th>
  </tr>

<% @decoded_polylines = JSON.parse(@polylines) %>
<% @decoded_polylines.each do |p| %>
  <tr>
    <td><%= p["activity_name"]%></td>
    <td><%= p["activity_started_at_date_time"]%></td>
    <td><%= link_to "show more", activity_show_path(p["id"] )%></td>
  </tr>
 
<% end %>

app/views/activity/show.html.erb
<% p = JSON.parse(@polyline) %>
<h1><%= p["activity_name"] %></h1>
<p>Find me in app/views/activity/show.html.erb</p>

<%= link_to "back to index", activity_index_path %>


<div id="map" style="width: 100%; height: 100%;">
hi <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br> <br> <br> <br> <br> <br> <br> <br><br><br> there
</div>

<pre>

title: <%= p["activity_name"] %>
started_at: <%= p["activity_started_at_date_time"] %>
activity_id: <%= p["activity_id"] %>
</pre>

<%= button_to "back", activity_index_path %>

<script>
window.encoded_polyline = "<%= j @polyline %>"
var polyline = JSON.parse(encoded_polyline)
var initialStyles = {
        color: "#1ef758",
        weight: 3,
        opacity: .7,
        lineJoin: 'round'
    }

var map = L.map('map').setView( [39.681635,-105.040421], 12);
L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 22,
        minZoom: 1,
        id: 'mapbox/satellite-v9',
        tileSize: 512,
        zoomOffset: -1,
        accessToken: 'pk.eyJ1Ijoiam9zaHdvcmtzIiwiYSI6ImNrcWk2NzUxeTJhbm8yem4weDFreTY5bjQifQ.Qja1F9B1-i7hK3KOvSYAvg'
      }).addTo(map);

  var coordinates = L.Polyline.fromEncoded(polyline["summary"]).getLatLngs();
  var line = L.polyline(
    coordinates, initialStyles
  ).addTo(map);

  // add marker to coordinates[0] and coordinates[-1]?

  marker = L.marker(coordinates[0]).addTo(map)
  marker = L.marker(coordinates[coordinates.length - 1]).addTo(map)


  map.fitBounds(line.getBounds());

  var popup = L.popup();
  popup.setContent(polyline["activity_name"]);
  
  line.on('mouseover', function(e){
    this.bindPopup(popup);
    popup.setLatLng(e.latlng).openOn(map);
    this.setStyle({
      color: "#EE4B2B",
      weight: 7,
      opacity: 5
    })
  });

  line.on('mouseout', function(e) {
    this.setStyle(initialStyles)
    e.target.closePopup();
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Josh's Mobility Data</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script type="text/javascript" src="https://rawgit.com/jieter/Leaflet.encoded/master/Polyline.encoded.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>